services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqaitorch
    container_name: freqtrade
    env_file:
      - .env
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./data/parquet:/data/parquet
    command: trade --config user_data/config.json
    restart: unless-stopped
    ports:
      - "8080:8080"

  ingestors:
    build: ./services/ingestors
    container_name: ingestors
    env_file:
      - .env
    volumes:
      - ./data/parquet:/data/parquet
      - ./user_data/freqai_data:/freqai_data
    command: ["bash","-c","python /app/run_all_ingestors.py"]
    restart: unless-stopped

  dashboard:
    build: ./services/dashboard
    container_name: dashboard
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data/parquet:/data/parquet
      - ./user_data:/freqtrade/user_data
    command: ["bash","-c","streamlit run app.py --server.address=0.0.0.0 --server.port=8501"]
    restart: unless-stopped

  gateway:
    build: ./services/gateway
    container_name: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./user_data:/freqtrade/user_data
    restart: unless-stopped

  telegram_bot:
    build: ./services/chat
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - freqtrade
    restart: unless-stopped
